# Generated by Django 5.0.6 on 2024-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('resort_name', models.CharField(max_length=255)),
                ('resort_image', models.FileField(null=True, upload_to='products')),
                ('resort_place', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contactus',
        ),
    ]
