# Generated by Django 5.0.6 on 2024-07-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_resorts_rename_contact_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='resorts',
            name='cat_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
