# Generated by Django 5.0.6 on 2024-07-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_resorts_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resorts',
            name='resort_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
