# Generated by Django 5.0.6 on 2024-07-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_resorts_resort_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=255)),
                ('reg_email', models.CharField(max_length=255)),
                ('reg_username', models.CharField(max_length=255, null=True)),
                ('reg_password', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
