# Generated by Django 5.0.6 on 2024-07-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('room_image', models.FileField(null=True, upload_to='media')),
                ('room_price', models.CharField(max_length=255)),
                ('room_capacity', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=255)),
                ('room_description', models.CharField(max_length=255)),
            ],
        ),
    ]
