# Generated by Django 5.0.6 on 2024-07-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_addrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='resorts',
            name='resort_rooms',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
