# Generated by Django 5.0.6 on 2024-07-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_resorts_resort_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrooms',
            name='resort_name',
            field=models.CharField(default='resort name', max_length=255),
        ),
    ]
