# Generated by Django 5.0.6 on 2024-07-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_addrooms_resort_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrooms',
            name='room_number',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='addrooms',
            name='room_status',
            field=models.CharField(default='available', max_length=255),
        ),
        migrations.AlterField(
            model_name='addrooms',
            name='room_capacity',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='addrooms',
            name='room_description',
            field=models.CharField(default='no disc', max_length=255),
        ),
        migrations.AlterField(
            model_name='addrooms',
            name='room_name',
            field=models.CharField(default='premium', max_length=255),
        ),
        migrations.AlterField(
            model_name='addrooms',
            name='room_price',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='addrooms',
            name='room_type',
            field=models.CharField(default='non ac', max_length=255),
        ),
    ]
