# Generated by Django 5.0.6 on 2024-07-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_addrooms_room_number_addrooms_room_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=255)),
                ('room_name', models.CharField(max_length=255)),
                ('book_image', models.FileField(null=True, upload_to='')),
                ('book_price', models.CharField(max_length=255)),
                ('book_number', models.CharField(max_length=255)),
                ('book_status', models.CharField(max_length=255)),
                ('book_capacity', models.CharField(max_length=255)),
                ('book_type', models.CharField(max_length=255)),
                ('book_description', models.CharField(max_length=255)),
                ('book_user', models.CharField(max_length=255)),
                ('book_adress', models.CharField(max_length=255)),
                ('payment_type', models.CharField(max_length=255, null=True)),
                ('order_status', models.CharField(max_length=255)),
            ],
        ),
    ]
