# Generated by Django 5.0.6 on 2024-08-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_bookroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='order_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
